# Generated by Django 3.0.6 on 2020-05-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='display_name',
            field=models.CharField(default=models.CharField(max_length=25, unique=True), max_length=25),
        ),
    ]
