# Generated by Django 3.0.6 on 2020-05-27 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=25, unique=True, validators=[django.core.validators.RegexValidator('^[^\\S]+$', code='invalid_username', message='No spaces allowed')]),
        ),
    ]
