# Generated by Django 3.0.6 on 2020-05-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200531_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='logo.png', upload_to='profile_pics'),
        ),
    ]
