# Generated by Django 3.0.6 on 2020-05-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(default='default_header.png', height_field='image_height', upload_to='blog_headers', width_field='image_width'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_height',
            field=models.IntegerField(default=1440),
        ),
        migrations.AddField(
            model_name='post',
            name='image_width',
            field=models.IntegerField(default=2560),
        ),
    ]
