# Generated by Django 3.0.6 on 2020-05-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200525_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(default='Whoops our author forgot to put a summary... Roast them in the comment secton!'),
        ),
    ]
