# Generated by Django 3.0.6 on 2020-05-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200528_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
